apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-management-tools
  labels:
    app: business-management-tools
spec:
  replicas: 3
  selector:
    matchLabels:
      app: business-management-tools
  template:
    metadata:
      labels:
        app: business-management-tools
    spec:
      containers:
      - name: business-management-tools
        image: business-management-tools:1.0
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret_key
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
      imagePullSecrets:
      - name: regcred
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: business-management-tools-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: business-management-tools
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi